### ISSUE TITLE
MODULE_NOT_FOUND error

### ISSUE THREAD

**Issue by kvegter** [grand-stack/graphql-architect#1]
I get this error in js console when starting the app:
```
ArchitectReality.ts:72 internal/modules/cjs/loader.js:625
  throw e;
  ^

Error: No valid exports main found for '/Users/keesv/Library/Application Support/Neo4j Desktop/Application/graphApps/grandstack/graphql-architect/dist/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/keesv/Library/Application Support/Neo4j Desktop/Application/graphApps/grandstack/graphql-architect/dist/node_modules/apollo-engine-reporting/dist/agent.js:26:16)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
}
```
I am running on a mac, can it be security settings? When I started the app it asked me multiple times to run java and node.js in the background.
Can it be something with the Permissions?

**Comment by johnymontana** [comment]
That sounds like it's missing a dependency that didn't get packaged with the release. @kvegter Do you still have this the latest version of GraphQL Architect (v0.0.19)?

The prompt for permission to run background process I think is a separate issue. We include `backgroundProcess` in the manifest, but I think we might be prompting before checking if the permission exists. I'll create an issue for that too
