### ISSUE TITLE
Infinite loading when lauching graphQL architect

### ISSUE THREAD

**Issue by digitaldave-dw** [grand-stack/graphql-architect#10]
Hello,

I have and issue while I want to start Graphql Architect. When I'am launching it it doeasn't start Grapql Server. iam using Neo4j Desktop 1.4.1 and my DB is 4.1.5. 
![image](https://user-images.githubusercontent.com/69633792/106271247-7e7c6a80-622f-11eb-91e4-8dd5b7347eef.png)

**Comment by johnymontana** [comment]
I believe this may be related to changes in the last Neo4j Desktop release. If you enable developer mode and open developer tools do you see any error messages?

**Comment by mfkilgore** [comment]
Adding same comment the I added to the community post here -- 

I tried again, and now see this message -

Graph App 'GraphQL Architect' can't be opened. See logs for more info (Developer menu in menu bar). Re-installing the app might resolve the issue.
Re-install GraphQL Architect and restart Neo4j Desktop.

the only obvious error in the log was -

2021-02-02 20:50:38.632] [info] [1] Online check response: 200 version: 1.4.1
files
[2021-02-02 20:50:56.910] [error] Graph-App 'GraphQL Architect' execution blocked: signature verification failure. {
constructor: 'Error',
stack: 'Error: Invalid content digest.\n' +
' at Object.exports.verifySignature (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/verify.js:141:15)\n' +
' at Object. (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/verify.js:27:36)\n' +
' at Generator.next ()\n' +
' at /Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/verify.js:7:71\n' +
' at new Promise ()\n' +
' at __awaiter (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/verify.js:3:12)\n' +
' at Object.exports.verify (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/verify.js:17:31)\n' +
' at Object. (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/index.js:43:35)\n' +
' at Generator.next ()\n' +
' at fulfilled (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/index.js:4:58)\n' +
' at runMicrotasks ()\n' +
' at processTicksAndRejections (internal/process/task_queues.js:85:5)'
}
[2021-02-02 20:51:18.363] [info] [1] Online check request: https://dist.neo4j.org/neo4j-desktop/win/latest.yml
[2021-02-02 20:51:19.131] [info] [1] Online check response: 200 version: 1.4.1
files
[2021-02-02 20:51:58.366] [info] [1] Online check request: https://dist.neo4j.org/neo4j-desktop/win/latest.yml
[2021-02-02 20:51:59.055] [info] [1] Online check response: 200 version: 1.4.1
files
[2021-02-02 20:52:38.365] [info] [1] Online check request: https://dist.neo4j.org/neo4j-desktop/win/latest.yml
[2021-02-02 20:52:38.698] [info] [1] Online check response: 200 version: 1.4.1
files

Let me know if you need more information or the entire log.

**Comment by magaton** [comment]
Have the same issue. It is loading forever. I have the latest version of the desktop and db

**Comment by doraig** [comment]
Having the same issue, had to down grade to 1.3.4 version of neo4j desktop.

**Comment by fuatu** [comment]
I have the same issue with version 1.4.1
upgrade of node and npm did not help

**Comment by XavierDK** [comment]
Same for me

**Comment by fuatu** [comment]
Deleting version 1.4.1 and all its leftovers, switching to an older version 1.3.4 solved the problem on macOS for me

**Comment by shriharip** [comment]
I am facing the same issue. Infinite loading on Macos catalina. node 7.7.0 and Version 1.4.3 (1.4.3.49)

**Comment by L-Botero** [comment]
> I believe this may be related to changes in the last Neo4j Desktop release. If you enable developer mode and open developer tools do you see any error messages?

I did as you asked, there seems to be an issue with the "AWSALB" cookie , attribute "SameSite" not being set up properly.

![image](https://user-images.githubusercontent.com/70966774/125126737-84715400-e0c9-11eb-95d7-d94cde53ac1f.png)

**Comment by rubyan** [comment]
I am having the same issue.

**Comment by SSSofyen** [comment]
I too, am stuck with this pickle =) 

I originally meant to use neo4j-graphql.js v2.6.0 as per this article : 
https://blog.grandstack.io/inferring-graphql-type-definitions-from-an-existing-neo4j-database-dadca2138b25
from william lyon, aka johnymontana in this thread.
That dependency turned out to be deprecated and internal node modules imports are disfunctional ... that won't do.

Is there no way to infer schemas from the db as of now ??? seems that way ... anyone ?

**Comment by jambler24** [comment]
Still an issue. Seems like the repo is dead, no updates.

**Comment by RyanMarr** [comment]
Same issue here. Any word on if this repo will be supported further?

**Comment by amarsanaag** [comment]
Same here. Is there anything to add from the developers?

**Comment by kristianmandrup** [comment]
@johnymontana I'm curious if the port is still correct?

If Neo4J Desktop, after creating a new database using latest DBMS (4.4.0)


```
Version | 4.4.0
-- | --
Edition | enterprise
Status | Active
IP address | localhost
Bolt port | 7687
HTTP port | 7474
HTTPS port | 7473
```

No mention of port `4000` in this list. However manually changing the port in Architect to one of the above doesn't seem to work either. Which port/protocol should it be using?
